"""Add is_verified on TenantSupportDocumment

Revision ID: 0236fd5cd3ff
Revises: 4ff9c7bd8b42
Create Date: 2025-09-15 15:06:40.981565

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0236fd5cd3ff'
down_revision: Union[str, Sequence[str], None] = '4ff9c7bd8b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_support_documents',
                  sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('tenants', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    existing_server_default=sa.text('true'))
    op.alter_column('tenants', 'is_deleted',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'is_deleted',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    existing_server_default=sa.text('false'))
    op.alter_column('tenants', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    existing_server_default=sa.text('true'))
    op.drop_column('tenant_support_documents', 'is_verified')
    # ### end Alembic commands ###
