"""Created Table mpesa_integrations

Revision ID: 0bcbe0ccaf84
Revises: 3ce8c1532169
Create Date: 2025-07-29 10:46:32.521677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bcbe0ccaf84'
down_revision: Union[str, Sequence[str], None] = '3ce8c1532169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
