"""Added is verified to mpesa integration model

Revision ID: 25c5b7f1a9e2
Revises: 9ef6e8a0b556
Create Date: 2025-08-05 03:19:39.528215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c5b7f1a9e2'
down_revision: Union[str, Sequence[str], None] = '9ef6e8a0b556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_integrations', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mpesa_integrations', 'is_verified')
    # ### end Alembic commands ###
