"""Update Donation model with donor, tenant, payment info

Revision ID: 291ff20abd2d
Revises: dc3df10c3c59
Create Date: 2025-07-29 22:07:51.024886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291ff20abd2d'
down_revision: Union[str, Sequence[str], None] = 'dc3df10c3c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

payment_method_enum = sa.Enum('MPESA', 'CARD', 'PAYPAL', 'BANK', name='paymentmethod')
payment_status_enum = sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='paymentstatus')


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type in PostgreSQL
    payment_method_enum.create(op.get_bind(), checkfirst=True)
    payment_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('donations', sa.Column('donor_id', sa.UUID(), nullable=True))
    op.add_column('donations', sa.Column('method',payment_method_enum , nullable=True))
    op.add_column('donations', sa.Column('status', payment_status_enum, nullable=True))
    op.add_column('donations', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    op.add_column('donations', sa.Column('callback_data', sa.JSON(), nullable=True))
    op.add_column('donations', sa.Column('is_anonymous', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_unique_constraint('uq_donations_transaction_id', 'donations', ['transaction_id'])
    op.create_foreign_key('fk_donations_tenant_id', 'donations', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key('fk_donations_donor_id', 'donations', 'users', ['donor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_donations_donor_id', 'donations', type_='foreignkey')
    op.drop_constraint('fk_donations_tenant_id', 'donations', type_='foreignkey')
    op.drop_constraint('uq_donations_transaction_id', 'donations', type_='unique')

    op.drop_column('donations', 'is_anonymous')
    op.drop_column('donations', 'callback_data')
    op.drop_column('donations', 'transaction_id')
    op.drop_column('donations', 'status')
    op.drop_column('donations', 'method')
    op.drop_column('donations', 'donor_id')
    op.drop_column('donations', 'tenant_id')

    # Drop enums explicitly
    # Drop the enum type from PostgreSQL
    payment_method_enum.drop(op.get_bind(), checkfirst=True)
    payment_status_enum.drop(op.get_bind(), checkfirst=True)
    # sa.Enum(name='paymentstatus').drop(op.get_bind())
    # ### end Alembic commands ###
