"""Added document base id

Revision ID: 303c9d815b32
Revises: 83eb3aac1d4e
Create Date: 2025-09-16 00:58:43.855767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303c9d815b32'
down_revision: Union[str, Sequence[str], None] = '83eb3aac1d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_support_documents', sa.Column('document_base_id', sa.String(), nullable=False))
    op.create_unique_constraint('uix_tenant_doc_base', 'tenant_support_documents', ['tenant_id', 'document_base_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_tenant_doc_base', 'tenant_support_documents', type_='unique')
    op.drop_column('tenant_support_documents', 'document_base_id')
    # ### end Alembic commands ###
