"""Added tenant website field

Revision ID: 3053e7a79173
Revises: 7591e62d66c6
Create Date: 2025-08-05 05:28:19.509743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3053e7a79173'
down_revision: Union[str, Sequence[str], None] = '7591e62d66c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'website')
    # ### end Alembic commands ###
