"""Add donations table

Revision ID: 3ce8c1532169
Revises: a95aee610b74
Create Date: 2025-07-17 14:13:01.900463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce8c1532169'
down_revision: Union[str, Sequence[str], None] = 'a95aee610b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('donor_name', sa.String(), nullable=True),
    sa.Column('donor_email', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('donated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donations')
    # ### end Alembic commands ###
