"""Add is_active, is_deleted to tenants + tenant_support_documents table

Revision ID: 4ff9c7bd8b42
Revises: ef2ff2ecc1ce
Create Date: 2025-09-15 14:36:09.055603

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ff9c7bd8b42'
down_revision: Union[str, Sequence[str], None] = 'ef2ff2ecc1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_support_documents',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.Column('document_name', sa.String(), nullable=False),
                    sa.Column('document_url', sa.String(), nullable=False),
                    sa.Column('document_type', sa.String(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('tenants', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'is_deleted')
    op.drop_column('tenants', 'is_active')
    op.drop_table('tenant_support_documents')
    # ### end Alembic commands ###
