"""Update Donation model to include donor_phone

Revision ID: 59feaf1ac865
Revises: 291ff20abd2d
Create Date: 2025-07-29 22:49:40.914818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59feaf1ac865'
down_revision: Union[str, Sequence[str], None] = '291ff20abd2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('donor_phone', sa.String(), nullable=True))
    op.alter_column('donations', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donations', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('donations', 'donor_phone')
    # ### end Alembic commands ###
