"""Created Table mpesa_integrations

Revision ID: 778be2192821
Revises: 0bcbe0ccaf84
Create Date: 2025-07-29 10:48:11.523624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778be2192821'
down_revision: Union[str, Sequence[str], None] = '0bcbe0ccaf84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('shortcode', sa.String(), nullable=False),
    sa.Column('consumer_key', sa.String(), nullable=False),
    sa.Column('consumer_secret', sa.String(), nullable=False),
    sa.Column('passkey', sa.String(), nullable=False),
    sa.Column('callback_url', sa.String(), nullable=False),
    sa.Column('account_reference', sa.String(), nullable=False),
    sa.Column('environment', sa.Enum('SANDBOX', 'PRODUCTION', name='environmenttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpesa_integrations_tenant_id'), 'mpesa_integrations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mpesa_integrations_tenant_id'), table_name='mpesa_integrations')
    op.drop_table('mpesa_integrations')
    # ### end Alembic commands ###
