"""made document url unique

Revision ID: 83eb3aac1d4e
Revises: e2d5ad001b7a
Create Date: 2025-09-16 00:08:01.085001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83eb3aac1d4e'
down_revision: Union[str, Sequence[str], None] = 'e2d5ad001b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tenant_support_documents', ['document_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_support_documents', type_='unique')
    # ### end Alembic commands ###
