"""mpesa integrations: tenant relationship

Revision ID: c1040f53e626
Revises: 778be2192821
Create Date: 2025-07-29 11:55:20.580967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1040f53e626'
down_revision: Union[str, Sequence[str], None] = '778be2192821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'mpesa_integrations', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mpesa_integrations', type_='foreignkey')
    # ### end Alembic commands ###
