"""Added tenant website unique attribute

Revision ID: ef2ff2ecc1ce
Revises: 3053e7a79173
Create Date: 2025-08-05 12:55:30.945098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2ff2ecc1ce'
down_revision: Union[str, Sequence[str], None] = '3053e7a79173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tenants', ['website'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    # ### end Alembic commands ###
